sudo: false

language: python

python:
  - 2.7
  - 3.5

env:
  - TOXENV=django111 AFTER_SUCCESS=codecov INSTALL_EXTRAS=codecov
  - TOXENV=django20
  - TOXENV=django21
  - TOXENV=django22

matrix:
 include:
  - python: 3.5
    env: TOXENV=quality
  - python: 3.5
    env: TOXENV=docs
 exclude:
  - python: 2.7
    env: TOXENV=django20
  - python: 2.7
    env: TOXENV=django21
  - python: 2.7
    env: TOXENV=django22


cache:
  - pip

install:
  - pip install -U pip wheel
  - make requirements
  - pip install pip ${INSTALL_EXTRAS}  # Installing just pip is a no-op

script:
  - make test

after_success:
  - true; ${AFTER_SUCCESS}  # "true; " on its own is no-op

deploy:
  provider: pypi
  user: edx
  password:
    secure: JIe1mYYcVSxe+57YJ7ZEmnoDTX16cGKOX37c2VcVJKT2rGFl8Fm/AxCeKe7260v2pcBIjRhB3OCPGHgvLVYG2bv0ib6yXJazvDmqwytPU9+Urhi27xkF2lynv+ZR2IMYA9azMtcmx3o5SB09m1/V8h1DrINayaFHcyUUCQOU91gD+0LktPYF8c0p1EFN9tuNDToC3uFlR/tP+YgRB1BHiKFN+/NXhxZlbwLFW4vXb8maiFYVao/CyRvgllN1HTVsF6u8/WX880jsb6gD/P8kTCIihVfqSBAt9X2isJqExbt4v1PH73Tn16/l633jz1XiHxJb4mDH7F+U0sHrEXcMsgUxqpZe/2trfQZGZwToDNQyR92Hm+34mV0UwTo8UyjavUQAwZILd1anz7mVN0H0hl9K71fBL0p9XXyd4/QUspG34ppHoPDf00mvynTCm7XFNvwqD96qokqxJ/6DR8dODcEeZP+2yrS+BDkJfbSNvHCftmQLNMXOj5LZW2HFpSAyISM4CpOJzn+WBaxNmGmkh+FsFN7dxs82KZyRnjYOaie9GRY+I7Tt4oYAl/iw0AOGhQkqzvQ413PadH0pdp5bj0Hr0wF8F8Zqmmz0qlJR4R6BNH36XClNhHVeuswvfCEM18AqRN0eGEPzkKrEUxJfU5MqRmxuotPLGbPo5Elfj9c=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.5
    condition: '$TOXENV = django111'
