sudo: false

language: python

python:
  - 2.7
  - 3.5

env:
  - TOXENV=django111

matrix:
 include:
  - python: 3.6
    env: TOXENV=quality,docs
    python: 3.6
    env: TOXENV=django111

cache:
  - pip

install:
  - pip install -U pip wheel codecov
  - make requirements

script:
  - make test

after_success:
  - codecov

deploy:
  provider: pypi
  user: edx
  password:
    secure: JIe1mYYcVSxe+57YJ7ZEmnoDTX16cGKOX37c2VcVJKT2rGFl8Fm/AxCeKe7260v2pcBIjRhB3OCPGHgvLVYG2bv0ib6yXJazvDmqwytPU9+Urhi27xkF2lynv+ZR2IMYA9azMtcmx3o5SB09m1/V8h1DrINayaFHcyUUCQOU91gD+0LktPYF8c0p1EFN9tuNDToC3uFlR/tP+YgRB1BHiKFN+/NXhxZlbwLFW4vXb8maiFYVao/CyRvgllN1HTVsF6u8/WX880jsb6gD/P8kTCIihVfqSBAt9X2isJqExbt4v1PH73Tn16/l633jz1XiHxJb4mDH7F+U0sHrEXcMsgUxqpZe/2trfQZGZwToDNQyR92Hm+34mV0UwTo8UyjavUQAwZILd1anz7mVN0H0hl9K71fBL0p9XXyd4/QUspG34ppHoPDf00mvynTCm7XFNvwqD96qokqxJ/6DR8dODcEeZP+2yrS+BDkJfbSNvHCftmQLNMXOj5LZW2HFpSAyISM4CpOJzn+WBaxNmGmkh+FsFN7dxs82KZyRnjYOaie9GRY+I7Tt4oYAl/iw0AOGhQkqzvQ413PadH0pdp5bj0Hr0wF8F8Zqmmz0qlJR4R6BNH36XClNhHVeuswvfCEM18AqRN0eGEPzkKrEUxJfU5MqRmxuotPLGbPo5Elfj9c=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.6
    condition: '$TOXENV = django111'
